### ISSUE TITLE
Add footer with a link to the source code.

### ISSUE THREAD

**Issue by Devansh-Baghel** [Devansh-Baghel/memory-game#1]
## Just make sure of these two things:

1. Footer should be its own component.
2. Footer should follow similar design as the rest of the website.

**Comment by Rehan52004** [comment]
please assign me this issue

**Comment by Devansh-Baghel** [comment]
@Rehan52004 assigned! just make sure the footer in only visible in the game winning screen or the game losing screeen and not on any other screen

**Comment by Rehan52004** [comment]
understand

**Comment by Rehan52004** [comment]
Is this project related to hacktoberfest?

**Comment by Rehan52004** [comment]
see sample footer.

![Screenshot 2023-10-04 130921](https://github.com/Devansh-Baghel/memory-game/assets/106008086/1015b10e-452d-4b3a-b97a-22083a27c144)

If its not that good than give me some idea or sample image

**Comment by Devansh-Baghel** [comment]
I want the footer to just be a floating div with rounded border with a link to the source code, kinna like this here:

![image](https://github.com/Devansh-Baghel/memory-game/assets/77718741/c02c0217-52b2-4590-8e32-992898d9ac85)

but in blueish color scheme.

**Comment by Devansh-Baghel** [comment]
> Is this project related to hacktoberfest?

Yes this repo is a part of hactoberfest.

**Comment by Rehan52004** [comment]
Ok

**Comment by Rehan52004** [comment]
please confirm.....


![Screenshot 2023-10-04 142243](https://github.com/Devansh-Baghel/memory-game/assets/106008086/0cd0b013-a11d-402f-a977-60314adf8fc8)

**Comment by Devansh-Baghel** [comment]
Looks good, make a pr, i'll merge it.
