### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aanchal-fatwani** [Devansh-Baghel/memory-game#2]
@Devansh-Baghel As part of HacktoberFest2023, I wish to update the ReadMe for this repository to present better information.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by Devansh-Baghel** [comment]
@aanchal-fatwani Sure! go ahead, and add a setup process in the readme, it should look like [this setup](https://github.com/Devansh-Baghel/todo#setup)
